name: TRM Design Studios
favicon: null
layout_spectrum: 0.50121
typography_spectrum: 0.74262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6eed7'
    - '#98b7a8'
    - '#020e28'
    - '#4d7c84'
    - '#29a8c9'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
