name: TRM Design Studios
favicon: null
layout_spectrum: 0.50121
typography_spectrum: 0.74262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#deceb5'
    - '#815120'
    - '#343331'
    - '#a47040'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
